const schedule = {
  weeks: {
    1: [
      {
        name: "Понедельник",
        date: "27 апреля",
        isToday: false,
        lessons: [
          {
            startTime: "08:00",
            endTime: "09:30",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "09:45",
            endTime: "11:15",
            isLection: false,
            discipline: "Микроэлектроника и схемотехника",
            teachers: ["Параскевов А. В.", "Алашеев В. В."],
            rooms: [],
            groups: ["ИТ2402/2", "ИТ2402/1"],
          },
          {
            startTime: "11:30",
            endTime: "13:00",
            isLection: false,
            discipline: "Мультимедиа технологии",
            teachers: ["Васильева А. Д."],
            rooms: [],
            groups: ["ИТ2303"],
          },
          {
            startTime: "13:50",
            endTime: "15:20",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "15:35",
            endTime: "17:05",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "17:20",
            endTime: "18:50",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
        ],
      },
      {
        name: "Вторник",
        date: "28 апреля",
        isToday: false,
        lessons: [
          {
            startTime: "08:00",
            endTime: "09:30",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "09:45",
            endTime: "11:15",
            isLection: false,
            discipline: "Микроэлектроника и схемотехника",
            teachers: ["Параскевов А. В.", "Алашеев В. В."],
            rooms: [],
            groups: ["ИТ2404/2", "ИТ2404/1"],
          },
          {
            startTime: "11:30",
            endTime: "13:00",
            isLection: false,
            discipline: "Инфокоммуникационные системы и сети",
            teachers: ["Лытнев Н. Н.", "Крепышев Д. А."],
            rooms: [],
            groups: ["ИТ2301/2", "ИТ2301/1"],
          },
          {
            startTime: "13:50",
            endTime: "15:20",
            isLection: false,
            discipline: "Микроэлектроника и схемотехника",
            teachers: ["Параскевов А. В.", "Алашеев В. В."],
            rooms: [],
            groups: ["ИТ2401/2", "ИТ2401/1"],
          },
          {
            startTime: "15:35",
            endTime: "17:05",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "17:20",
            endTime: "18:50",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
        ],
      },
      {
        name: "Среда",
        date: "29 апреля",
        isToday: false,
        lessons: [
          {
            startTime: "08:00",
            endTime: "09:30",
            isLection: false,
            discipline: "Базы данных",
            teachers: ["Попова М. И.", "Ткаченко В. В."],
            rooms: [],
            groups: ["ПИ2403/2", "ПИ2403/1"],
          },
          {
            startTime: "09:45",
            endTime: "11:15",
            isLection: false,
            discipline: "Базы данных",
            teachers: ["Попова М. И.", "Ткаченко В. В."],
            rooms: [],
            groups: ["ПИ2401/2", "ПИ2401/1"],
          },
          {
            startTime: "11:30",
            endTime: "13:00",
            isLection: false,
            discipline: "Базы данных",
            teachers: ["Попова М. И.", "Ткаченко В. В."],
            rooms: [],
            groups: ["ПИ2402/2", "ПИ2402/1"],
          },
          {
            startTime: "13:50",
            endTime: "15:20",
            isLection: false,
            discipline: "Базы данных",
            teachers: ["Попова М. И.", "Ткаченко В. В."],
            rooms: [],
            groups: ["ПИ2404/2", "ПИ2404/1"],
          },
          {
            startTime: "15:35",
            endTime: "17:05",
            isLection: false,
            discipline: "Информационная безопасность",
            teachers: ["Алашеев В. В."],
            rooms: [],
            groups: ["ПИ2404"],
          },
          {
            startTime: "17:20",
            endTime: "18:50",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
        ],
      },
    ],
    2: [
      {
        name: "Понедельник",
        date: "20 апреля",
        isToday: true,
        lessons: [
          {
            startTime: "08:00",
            endTime: "09:30",
            isLection: true,
            discipline: "Компьютерные системы",
            teachers: ["Сергеев А. Э."],
            rooms: [],
            groups: ["ИТ2401/2"],
            isNow: true,
          },
          {
            startTime: "09:45",
            endTime: "11:15",
            isLection: false,
            discipline: "Компьютерные системы",
            teachers: ["Сергеев А. Э.", "Аршинов Г. А."],
            rooms: [],
            groups: ["ИТ2402/2", "ИТ2402/1"],
          },
          {
            startTime: "11:30",
            endTime: "13:00",
            isLection: false,
            discipline: "Основы математической логики и теории алгоритмов",
            teachers: ["Аршинов Г. А."],
            rooms: [],
            groups: ["ИТ2501"],
          },
          {
            startTime: "13:50",
            endTime: "15:20",
            isLection: false,
            discipline: "Основы математической логики и теории алгоритмов",
            teachers: ["Аршинов Г. А."],
            rooms: [],
            groups: ["ИТ2502"],
          },
          {
            startTime: "15:35",
            endTime: "17:05",
            isLection: false,
            discipline: "Вычислительные системы, сети и телекоммуникации",
            teachers: ["Алашеев В. В."],
            rooms: [],
            groups: ["ПИ2503/1"],
          },
          {
            startTime: "17:20",
            endTime: "18:50",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
        ],
      },
      {
        name: "Вторник",
        date: "21 апреля",
        isToday: false,
        lessons: [
          {
            startTime: "08:00",
            endTime: "09:30",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "09:45",
            endTime: "11:15",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "11:30",
            endTime: "13:00",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "13:50",
            endTime: "15:20",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "15:35",
            endTime: "17:05",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
          {
            startTime: "17:20",
            endTime: "18:50",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
        ],
      },
      {
        name: "Среда",
        date: "22 апреля",
        isToday: false,
        lessons: [
          {
            startTime: "08:00",
            endTime: "09:30",
            isLection: false,
            discipline: "Основы математической логики и теории алгоритмов",
            teachers: ["Аршинов Г. А.", "Авакимян Н. Н."],
            rooms: [],
            groups: ["ИТ2504/1", "ИТ2504/2"],
          },
          {
            startTime: "09:45",
            endTime: "11:15",
            isLection: false,
            discipline: "Основы математической логики и теории алгоритмов",
            teachers: ["Аршинов Г. А.", "Авакимян Н. Н."],
            rooms: [],
            groups: ["ИТ2502/1", "ИТ2502/2"],
          },
          {
            startTime: "11:30",
            endTime: "13:00",
            isLection: false,
            discipline: "Основы математической логики и теории алгоритмов",
            teachers: ["Аршинов Г. А.", "Авакимян Н. Н."],
            rooms: [],
            groups: ["ИТ2503/1", "ИТ2503/2"],
          },
          {
            startTime: "13:50",
            endTime: "15:20",
            isLection: false,
            discipline: "Алгоритмы и структуры данных",
            teachers: ["Попок Л. Е."],
            rooms: [],
            groups: ["ЦР2502/2"],
          },
          {
            startTime: "15:35",
            endTime: "17:05",
            isLection: false,
            discipline: "Вычислительные системы, сети и телекоммуникации",
            teachers: ["Алашеев В. В.", "Крепышев Д. А."],
            rooms: [],
            groups: ["ПИ2502/1", "ПИ2502/2"],
          },
          {
            startTime: "17:20",
            endTime: "18:50",
            isLection: false,
            discipline: "",
            teachers: [],
            rooms: [],
            groups: [],
          },
        ],
      },
    ],
  },
  currentWeek: 2,
};

export default schedule;
